# Generated by Django 2.0.5 on 2018-05-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attends',
            field=models.BooleanField(verbose_name='Ich komme!'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='brings',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ich bringe mit'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Anzahl Personen'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
