# Generated by Django 2.0.5 on 2018-05-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180522_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Anzahl Personen'),
        ),
    ]
